# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://kenshih.github.io/nbdev_ken/"

git_url = "https://github.com/kenshih/nbdev_ken/tree/main/"

def custom_doc_links(name): return None
